apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-rust
  labels:
    app: {{ $.Release.Name }}-rust
    platform: rust
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5005
    protocol: TCP
    name: http
  selector:
    app: {{ $.Release.Name }}-rust
