services:
  nginx:
    image: nginx:alpine
    container_name: multi-platform-nginx
    ports:
      - "8080:80"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dotnet
      - nodejs
      - python
      - java
      - go
      - rust
      - websocket
      - react-signup
    networks:
      - app-network

  dotnet:
    build:
      context: .
      dockerfile: dotnet/Dockerfile
    container_name: multi-platform-dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./dotnet
          target: /app
          ignore:
            - bin/
            - obj/
        - action: sync
          path: ./shared
          target: /shared
        - action: rebuild
          path: ./dotnet/HelloWorld.csproj

  nodejs:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    container_name: multi-platform-nodejs
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./nodejs
          target: /app
          ignore:
            - node_modules/
        - action: sync
          path: ./shared
          target: /shared
        - action: rebuild
          path: ./nodejs/package.json

  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: multi-platform-python
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./python
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: sync
          path: ./shared
          target: /shared
        - action: rebuild
          path: ./python/requirements.txt

  java:
    build:
      context: .
      dockerfile: java/Dockerfile
    container_name: multi-platform-java
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./java/src
        - action: rebuild
          path: ./java/pom.xml
        - action: sync
          path: ./shared
          target: /shared

  go:
    build:
      context: .
      dockerfile: go/Dockerfile
    container_name: multi-platform-go
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./go
          ignore:
            - "*.exe"
        - action: sync
          path: ./shared
          target: /shared

  rust:
    build:
      context: .
      dockerfile: rust/Dockerfile
    container_name: multi-platform-rust
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./rust/src
        - action: rebuild
          path: ./rust/Cargo.toml
        - action: sync
          path: ./shared
          target: /shared

  websocket:
    build:
      context: .
      dockerfile: websocket/Dockerfile
    container_name: multi-platform-websocket
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./websocket
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./websocket/package.json

  react-signup:
    build:
      context: ./react-signup
      dockerfile: Dockerfile
    container_name: multi-platform-react-signup
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./react-signup/src
          target: /app/src
        - action: rebuild
          path: ./react-signup/package.json

networks:
  app-network:
    driver: bridge
