services:
  nginx:
    image: nginx:alpine
    container_name: multi-platform-nginx
    ports:
      - "8080:80"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dotnet
      - nodejs
      - python
      - java
      - go
      - websocket
    networks:
      - app-network

  dotnet:
    build:
      context: .
      dockerfile: dotnet/Dockerfile
    container_name: multi-platform-dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    container_name: multi-platform-nodejs
    networks:
      - app-network

  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: multi-platform-python
    networks:
      - app-network

  java:
    build:
      context: .
      dockerfile: java/Dockerfile
    container_name: multi-platform-java
    networks:
      - app-network

  go:
    build:
      context: .
      dockerfile: go/Dockerfile
    container_name: multi-platform-go
    networks:
      - app-network

  websocket:
    build:
      context: .
      dockerfile: websocket/Dockerfile
    container_name: multi-platform-websocket
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
