replicaCount: 1

image:
  repository: multi-platform-java
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5003

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
