apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-go
  labels:
    app: {{ $.Release.Name }}-go
    platform: go
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5004
    protocol: TCP
    name: http
  selector:
    app: {{ $.Release.Name }}-go
