apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-dotnet
  labels:
    app: {{ $.Release.Name }}-dotnet
    platform: dotnet
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-dotnet
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-dotnet
        platform: dotnet
    spec:
      containers:
      - name: dotnet
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          protocol: TCP
        {{- if .Values.env }}
        env:
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
