apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-java
  labels:
    app: {{ $.Release.Name }}-java
    platform: java
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: {{ $.Release.Name }}-java
