apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-websocket
  labels:
    app: {{ $.Release.Name }}-websocket
    platform: websocket
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8081
    protocol: TCP
    name: ws
  selector:
    app: {{ $.Release.Name }}-websocket
