replicaCount: 1

image:
  repository: multi-platform-go
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5004

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
