apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-nodejs
  labels:
    app: {{ $.Release.Name }}-nodejs
    platform: nodejs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-nodejs
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-nodejs
        platform: nodejs
    spec:
      containers:
      - name: nodejs
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5001
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
