apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-nodejs
  labels:
    app: {{ $.Release.Name }}-nodejs
    platform: nodejs
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: {{ $.Release.Name }}-nodejs
