replicaCount: 1

image:
  repository: multi-platform-rust
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5005

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
