name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Prepare gh-pages branch
        run: |
          # Check if gh-pages branch exists
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf .

            # Create initial index.html
            cat > index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=https://github.com/${{ github.repository }}">
              <title>Redirecting...</title>
          </head>
          <body>
              <p>Redirecting to <a href="https://github.com/${{ github.repository }}">repository</a>...</p>
          </body>
          </html>
          EOF

            # Create empty index.yaml
            cat > index.yaml <<EOF
          apiVersion: v1
          entries: {}
          generated: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          EOF

            git add index.html index.yaml
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages

            # Switch back to main
            git checkout main
          else
            echo "gh-pages branch already exists"
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm
          config: .github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy landing page
        run: |
          if [ -f docs/index.html ]; then
            cp docs/index.html gh-pages/index.html
            cd gh-pages
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add index.html
            if git diff --staged --quiet; then
              echo "No changes to landing page"
            else
              git commit -m "Update landing page"
              git push origin gh-pages
            fi
          fi
